### PR TITLE
Godot 4.0 support

### PR DESCRIPTION
**Pull request by thomasgauthier**
# Global changes

- removed type annotations in scripts as it was causing compilation errors
- changed `VisualShaderNode.PORT_TYPE_VECTOR` references to `VisualShaderNode.PORT_TYPE_VECTOR_3D`

# Specific changes

`addons/shaderV/tools/random/randomGoldNoiseFloat.gdshader`
- removed PI definition as it is now built-in

`addons/shaderV/rgba/bloom.gd`
`addons/shaderV/tools/random/randomGoldNoiseFloat.gd`

- added a semicolon in the generated code

`addons/shaderV/rgba/generate_shapes/scanLinesSharp.gd` `addons/shaderV/rgba/generate_shapes/stripesRandom.gd`

- added cast to float in generated code

`addons/shaderV/uv/animated/tilingNoffsetAnimated.gd`

- changed `+=` to `=` in generated code

# Visual shaders

## Sobel Edge
- connected new white constant to output

## Color Correction Adjustment
- added gradient as parameter

## Hash Random Vector 2D and Vector2 Compose
- added VectorDecompose and VectorCompose to preserve blue value of 1 that was the default in 3.x

### CODE REVIEW

**Comment by Ludmuterol** [comment]
Thank you for this! saved me some work though i had another problem. I tried using worley3d with the default values:
```
  151 | void fragment() {
  152 |  float n_out12p0;
  153 |  float n_out12p1;
  154 | 
  155 |  vec3 n_in12p1 = vec3(0.00000, 0.00000, 0.00000);
  156 |  int n_in12p2 = 5;
  157 |  int n_in12p3 = 1;
  158 |  int n_in12p4 = 0;
  159 |  {
E 160->  vec2 n_out12p0n_out12p1 = _cellular3dNoiseFunc(vec3((UV.xy+n_in12p1.xy)*n_in12p2, n_in12p4), min(max(n_in12p3, 0.0), 1.0));
  161 |  n_out12p0 = n_out12p0n_out12p1.x;
  162 |  n_out12p1 = n_out12p0n_out12p1.y;
  163 |  }
  164 | 
  165 | 
  166 |  COLOR.rgb = vec3(n_out12p0);
  167 | }
  168 | 
  :160 - Invalid arguments to operator '*': 'vec2, int'.
  Shader compilation failed.
```

  I could stop the error from appearing by changing the init func default values to floats.:

```
func _init():
	set_input_port_default_value(1, Vector3(0.0, 0.0, 0.0))
	set_input_port_default_value(2, 5.0)
	set_input_port_default_value(3, 1.0)
	set_input_port_default_value(4, 0.0)
```

looking through the other files it seemed like a random choosing between floats and ints as defaults. Is there a reason someone would want to choose an int as a defaultvalue for a VisualShaderNode.PORT_TYPE_SCALAR? or is it just something i happen to be the first one to notice?

**Comment by arkology** [comment]
@thomasgauthier thanks a lot!
Could you please check error @Ludmuterol mentioned? Maybe it will be better to change every default port to float which supposed to be float. I didn't face this problem before so didn't care about this - maybe in 4.0 something was changed in Godot.
Could you also check if it is possible to change `.gdshader` to `.gdshaderinc` and change global code section to inclusion of `.gdshaderinc` file? But if it will break something or take a lot of time I think it could be left as it is now.

**Comment by thomasgauthier** [comment]
I also had problems with scalar input being treated as ints instead of floats. Changing all relevant inputs to floats explicitly as @arkology suggested probably would fix it. I can try this.

@arkology I can do  the `.gdshaderinc` change over the weeked. I'll post updates here.

**Comment by thomasgauthier** [comment]
Just got to this now. 6f5cabf has the `.gdshaderinc` change and the float problem fixed

**Comment by arkology** [comment]
@thomasgauthier thanks! I'll test it at the weekend and merge into master

**Review by arkology — APPROVED** [review]
I quickly ran through the changes and overall everything looks great! If something is wrong, it can be fixed later, but right now I think it's ready for merge🎉

**Comment by arkology** [comment]
Thanks!

**Pull request merged**
